version: '3'
services:
  server27:
    container_name: myapp27
    restart: always
    build: ./server1
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo27:27017/vrp27
      - PORT=3001
      - JWT_SECRET=jwtSecret
    volumes:
      - ./server1/upload:/usr/src/app/upload
      - ./server1/data/backupData:/usr/src/app/data/backupData
    links:
      - mongo27
  mongo27:
    container_name: mymongo27
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/mydb:/data/db

networks: 
  default: 
    external: 
      name: external-network27